services:
  accessmonitor-backend:
    image: acessibilidade/accessmonitor-api:1.0.0
    container_name: accessmonitor-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      REFERER: "http://localhost:3000"
      IP_BLACKLIST_RANGES: ""
      RATE_LIMIT_ENABLED: false
      RATE_LIMIT_TTL: 60000
      RATE_LIMIT_LIMIT: 10
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - access-monitor-network


  wrapper-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wrapper-api
    ports:
      - "5297:5297"
    environment:
      - AccessMonitor__BaseUrl=http://accessmonitor-backend:3000
      - AccessMonitor__Referer=http://localhost:3000
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      accessmonitor-backend:
        condition: service_healthy
    networks:
      - access-monitor-network

networks:
  access-monitor-network:
    driver: bridge